- name: To install components related to CI
  hosts: cintegration
  roles:
    - role: epel
      redhat_extra_module:
        - module: libselinux-python
    - role: jdkext
    - role: jenkins
    - role: ansible
