- name: To install components needed by Notification Real Time application
  hosts: mongodbserver
  roles:
    - role: epel
      redhat_extra_module:
        - module: libselinux-python
    - role: mongodb
