- name: To install components needed by Notification Real Time application
  hosts: realtime
  roles:
    - role: epel
      redhat_extra_module:
        - module: libselinux-python
    - role: node
      nodejs_extra_modules:
      - module: pm2
      - module: express
      - module: bower
      - module: grunt
    - role: git
