- name: To install components needed by Notification Real Time application
  hosts: realtime
  roles:
    - role: epel
    - role: node
      nodejs_extra_modules:
      - module: pm2
    - role: git
