---
# tasks file for node
- name: Installing node
  yum: name=npm state=present enablerepo=epel
  sudo: yes

- name: Installing basic extra modules
  npm: global=yes name={{ item.module }} state=present
  with_items: nodejs_extra_modules
  sudo: yes
